version: '3.8'

services:
  djangoapp:
    build:
      context: .
    container_name: djangoapp
    volumes:
      - ./src:/app  # Mounts ./src (host) to /app (container)
    working_dir: /app  # Sets the working directory to /app
    command: sh -c "python prj/manage.py makemigrations && python prj/manage.py migrate && python prj/manage.py runserver 0.0.0.0:8000"
    ports:
      - "127.0.0.1:23048:8000"  # Port Django = matricule (23048)
    depends_on:
      mydb:
        condition: service_healthy

  mydb:
    image: mysql
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
    ports:
      - "127.0.0.1:24048:3306"  # Port MySQL = matricule + 1000 (24048)
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10